Added "Purge" to CDNsites
NCCloud/pystackpath pull request #4
Opened 2019-10-08 17:09 UTC by ostcrom

Implemented "Purge" endpoint to CDN Sites class.

2019-10-08 17:17 UTC, ghost requested changes
.DS_Store file should not be included. Can you remove it pls?

2019-10-08 18:07 UTC, ostcrom commented
Thank you for the guidance. Please let me know if the changes I have just pushed are acceptable.

2019-10-08 18:10 UTC, ghost approved these changes

2019-10-09 07:10 UTC, prometherion commented on pystackpath/cdnsites.py
> +        data = {"items": [
Please, indent correctly dictionary following [PEP8 style guide](https://www.python.org/dev/peps/pep-0008/#indentation):
```
data = {
    "items": [
        {
            "url": url,
            "recursive": recursive,
            "headers": headers,
            "invalidateOnly": invalidateOnly,
            "purgeSelector": purgeSelector
        }
    ]
}
```

2019-10-09 07:19 UTC, sandromodarelli commented
thank you @ostcrom. please, add a row on README about CDN cache purge.
wdyt about add the GetPurgeStatus, too? https://developer.stackpath.com/en/api/cdn/#operation/GetPurgeStatus

2019-10-09 15:15 UTC, ostcrom commented
Thank you for the feedback, I have made the changes requested. Please let me know if any further revision is needed.

2019-10-10 05:26 UTC, prometherion approved these changes
LGTM

2019-10-10 06:56 UTC, sandromodarelli approved these changes

2019-10-10 06:58 UTC, merged